### ISSUE TITLE
About Pyclomap Error

### ISSUE THREAD

**Issue by pegasus2004** [onpix/LLNeRF#19]
I follow the instruction to git the available Pyclomap by ' git clone https://github.com/rmbrualla/pycolmap.git ./internal/pycolmap' However, It still report error, confusing me a lot, could you help me find why would exist this problem?      thanks a lot.                  Traceback (most recent call last):
  File "/home/zhangmeng/.conda/envs/llnerf/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhangmeng/.conda/envs/llnerf/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zhangmeng/keyan/LLNeRF/train.py", line 314, in <module>
    app.run(main)
  File "/home/zhangmeng/.conda/envs/llnerf/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/zhangmeng/.conda/envs/llnerf/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/zhangmeng/keyan/LLNeRF/train.py", line 67, in main
    dataset = datasets.load_dataset('train', config.data_dir, config)
  File "/home/zhangmeng/keyan/LLNeRF/internal/datasets.py", line 54, in load_dataset
    return dataset_dict[config.dataset_loader](split, train_dir, config)
  File "/home/zhangmeng/keyan/LLNeRF/internal/datasets.py", line 297, in __init__
    self._load_renderings(config)
  File "/home/zhangmeng/keyan/LLNeRF/internal/datasets.py", line 588, in _load_renderings
    pose_data = NeRFSceneManager(colmap_dir).process()
  File "/home/zhangmeng/keyan/LLNeRF/internal/datasets.py", line 80, in process
    self.load_images()
  File "/home/zhangmeng/keyan/LLNeRF/internal/pycolmap/pycolmap/scene_manager.py", line 131, in load_images
    self._load_images_bin(input_file)
  File "/home/zhangmeng/keyan/LLNeRF/internal/pycolmap/pycolmap/scene_manager.py", line 162, in _load_images_bin
    points_array.fromfile(f, 3 * num_points2D)
ValueError: bytes length not a multiple of item size

**Comment by pegasus2004** [comment]
I have found why exists this problem, maybe when I uploaded the .bin files to remote server, the upload was interrupt
ted, thanks! But when I am training, the needed momery is so large, my GPU can't serve that. How can I change training config to make needed momery smaller?
